### ISSUE TITLE
PCB for NPNA Board connections

### ISSUE THREAD

**Issue by D4veBowm4n** [sternflyer/stratux-NPNA#2]
This is a really interesting port of the stratux project - I'd like to build one since my RPi went kaput. Would you be willing to share the PCB layout you designed? Or at least the schematic for connecting the SDRs + GPS + AHRS board?

**Comment by sternflyer** [comment]
Added the PCB files and a partlist for the components.
However, this is still work in progress.
I'm currently seeing issues with the GPS-signal dropping when enabling the SDRs. Hence the ferrite beads on the PCB. It helps a bit, but signal still drops significantly.

**Comment by D4veBowm4n** [comment]
Ok, thank you - I'll check it out!
